name: Update README

on:
  push:
    branches: [ main ]
    paths-ignore:
      - 'README.md'
      - 'assets/**'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    concurrency:
      group: update-readme
      cancel-in-progress: true
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Generate README
        run: python scripts/generate_readme.py

      - name: Commit changes
        run: |
          git config user.name "actions-bot"
          git config user.email "actions@users.noreply.github.com"
          git add README.md assets/lang_pie.png assets/heatmap.png assets/tags_cloud.png
          git diff --cached --quiet || git commit -m "chore: auto-update README [skip ci]"
          git push
        